name: Complex Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo "Job 1 completed"

  job2:
    needs: job1
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo "Job 2 completed"

  job3:
    needs: job2
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo "Job 3 completed"

  job4:
    needs: job3
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo "Job 4 completed"

  job5:
    needs: job4
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo "Job 5 completed"

  job6:
    needs: job5
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo "Job 6 completed"

  job7:
    needs: job6
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo "Job 7 completed"

  job8:
    needs: job7
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo "Job 8 completed"

  job9:
    needs: job8
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo "Job 9 completed"

  job10:
    needs: job9
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo "Job 10 completed"
